### ISSUE TITLE
Implement Basic System View Rendering

### ISSUE THREAD

**Issue by KerbalJeb** [Tableu/Bismarck#43]
**Implement a basic prototype of the system view**
- [x] Draw Planets & Orbit Lines
    - [x] Figure out if pixel art will work/look ok or if vector style graphics are needed
- [x] Camera Panning & Zooming
   - [x] Left click drag to pan with constrained panning area
   - [x] Scroll wheel to zoom with constrained range
- [x] Fixed Size Map Icons (for ship, planets, ect. the size of these objects should not change with zoom level)

**Comment by KerbalJeb** [comment]
@Tableu 
There does not seem to be an easy way to adjust the zoom of a pixel perfect camera at runtime (I guess since then it wouldn't be pixel perfect), so making orbit lines/map icons appear in a pixel art style won't be straight forward. I've got a couple ideas of how we could do it, but first someone should draw some full mock-ups of the system map to make sure it will actually look better as pixel art.

**Comment by Tableu** [comment]
I can ask for some pixel art planets
